# Generated by Django 5.0 on 2023-12-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="doors",
            field=models.CharField(
                choices=[("2", "2"), ("3", "3"), ("4", "4"), ("5", "5"), ("6", "6")],
                max_length=100,
            ),
        ),
    ]
