# Generated by Django 5.0 on 2023-12-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car", "0006_alter_car_featured"),
    ]

    operations = [
        migrations.RemoveField(model_name="car", name="featured",),
    ]
